import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
    en: {
        auth: {
            appName: "ATCE DRIVER",
            welcome: "Welcome",
            loginSubtitle: "Sign in to manage your trips and deliveries",
            emailLabel: "Email Address",
            emailPlaceholder: "Enter your email",
            emailRequired: "Email is required",
            invalidEmail: "Please enter a valid email address",
            passwordLabel: "Password",
            passwordPlaceholder: "Enter your password",
            passwordRequired: "Password is required",
            passwordMin: "Password must be at least 6 characters",
            passwordMin8: "Password must be at least 8 characters",
            forgotPassword: "Forgot Password?",
            backToLogin: "Back to Login",
            signIn: "Sign In",
            loginSuccess: "Login successful",
            loginFailed: "Login failed",
            enterCredentials: "Please enter email and password",
            forgotTitle: "Forgot Password",
            forgotSubtitle: "Enter your email address and we'll send you an OTP to reset your password",
            sendOtp: "Send OTP",
            otpSent: "OTP sent to your email",
            otpFailed: "Failed to send OTP",
            otpError: "Unable to send OTP. Please try again.",
            otpSendFailed: "Failed to send OTP",
            otpSendError: "Unable to send OTP. Please try again.",
            resetTitle: "Reset Password",
            resetSubtitle: "Enter the OTP sent to your email and create your new password",
            otpLabel: "OTP Code",
            otpPlaceholder: "Enter 6-digit OTP",
            otpRequired: "OTP is required",
            otpInvalid: "OTP must be 6 digits",
            invalidOtp: "Invalid OTP",
            newPasswordLabel: "New Password",
            newPasswordPlaceholder: "Enter new password",
            confirmPasswordLabel: "Confirm Password",
            confirmPasswordPlaceholder: "Confirm new password",
            confirmRequired: "Please confirm your password",
            passwordMismatch: "Passwords do not match",
            resetSuccess: "Password reset successfully",
            resetFailed: "Unable to reset password. Please try again.",
            didntReceive: "Didn't receive code?",
            resendOtp: "Resend OTP",
            resendIn: "Resend OTP in",
            otpResent: "OTP resent to your email",
        },
        todo: {
            goodMorning: "Good Morning",
            goodAfternoon: "Good Afternoon",
            goodEvening: "Good Evening",
            activeTrip: "Active Trip",
            totalTrips: "Total Trips",
            viewTripDetails: "VIEW TRIP DETAILS",
            noActiveTrips: "No Active Trips",
            noActiveTripsSubtitle: "You don't have any trips assigned yet. Pull down to refresh.",
            ton: "TON",
            na: "NA",
            tabLabel: "Trips",
            todo: "To-Do",
            history: "History",
            profile: "Profile"
        },
        tripDetail: {
            title: "Trip Details",
            loading: "Loading trip details...",
            noData: "No trip data available",
            orderDetails: "Order Details",
            tripId: "Trip ID",
            orderId: "Order ID",
            vehicle: "Vehicle",
            weight: "Weight",
            ton: "TON",
            activeLog: "Active Log",
            assigned: "Assigned",
            started: "Started",
            completed: "Completed",
            pickupLocation: "Pickup Location",
            deliveryLocation: "Delivery Location",
            locationNotSpecified: "Location not specified",
            noContactInfo: "No contact information available",
            call: "Call",
            navigate: "Navigate",
            weightLoadInfo: "Weight & Load Information",
            deliveredWeight: "Delivered Weight",
            assignedWeight: "Assigned",
            load: "Load",
            material: "Material",
            na: "NA",
            paymentDetails: "Payment Details",
            totalAmount: "Total Amount",
            distance: "Distance",
            sliding: "Sliding...",
            startTrip: "Start Trip",
            slideStartTrip: "Slide to Start Trip",
            slideMarkLoaded: "Slide to Mark Loaded",
            slideMarkArrived: "Slide to Mark Arrived",
            slideCompleteTrip: "Slide to Complete Trip",
            slideDefault: "Slide",
            tripStartedSuccess: "Trip started successfully!",
            invalidStatus: "Trip cannot be started from current status",
        },
        tripInProgress: {
            title: "Trip In Progress",
            fetchingLocation: "Fetching current location...",
            route: "Route",
            status: "Status",
            na: "N/A",
            truck: "Truck",
            destination: "Destination",
            estimatedArrival: "Estimated Arrival",
            distance: "Distance",
            deliveryLocation: "Delivery Location",
            contactPerson: "Contact Person",
            markArrived: "Mark as Arrived",
            minutesShort: "min",
            hoursShort: "hours",
        },
        profile: {
            personalInformation: "Personal Information",
            accountOrganization: "Account & Organization",
            documents: "Documents",
            fullName: "Full Name",
            email: "Email",
            phoneNumber: "Phone Number",
            userType: "User Type",
            companyName: "Company Name",
            vehicleRegNumber: "Vehicle Registered Number",
            signOut: "Sign Out",
            cancel: "Cancel",
            logoutConfirmTitle: "Sign Out",
            logoutConfirmMessage: "Are you sure you want to sign out? You'll need to sign in again to access your trips.",
            na: "N/A",
            loggedOutSuccess: "Logged out successfully",
            tabLabel: "Profile",
        },
        notifications: {
            title: "Notifications",
            unread: "unread",
            markAllRead: "Mark all read",
            deleteAll: "Delete all",
            delete: "Delete",
            noNotifications: "No notifications yet",
            loading: "Loading...",
        },
        markComplete: {
            header: "Mark as Complete",
            orderDetails: "Order Details",
            tripId: "Trip ID",
            orderId: "Order ID",
            customer: "Customer",
            vehicle: "Vehicle",
            weight: "Weight",
            deliveryAddress: "Delivery Address",
            contact: "Contact",
            deliveryProgress: "Delivery Progress",
            pickup: "Pickup",
            loaded: "Loaded",
            arrived: "Arrived",
            complete: "Complete",
            unloadedWeightLabel: "Unloaded Weight (TON)",
            unloadedWeightPlaceholder: "Enter unloaded weight",
            proofTitle: "Proof of Delivery",
            proofSubtitle: "Capture photo of delivered parcel",
            markButton: "Mark as Complete",
            uploadPhoto: "Please upload delivery photo",
            enterWeight: "Please enter unloaded weight",
            failed: "Failed to complete trip",
            completed: "Trip completed successfully",
            tripCompleted: "Trip Completed",
            deliverySuccess: "Delivery Successful 🎉",
            uploaded: "photo(s) uploaded successfully.",
            done: "Completed",
        },
        markLoad: {
            markAsLoaded: "Mark as Loaded",
            accessingLocation: "Accessing location...",
            locationRequired: "Location Required",
            enableLocation: "Enable location services to continue",
            retry: "Retry",
            tripLoading: "Trip Loading...",
            ready: "READY",
            pending: "PENDING",
            allItemsLoaded: "All items loaded properly and ready for delivery",
            tripNumber: "Trip Number",
            totalWeight: "Total Weight",
            loadedWeightLabel: "Loaded Weight (TON)",
            loadedWeightPlaceholder: "Enter loaded weight",
            uploadDocuments: "Upload Documents",
            uploadSubtitle: "Capture or select photos for the loading process",
            processing: "Processing...",
            uploading: "Uploading...",
            markTripLoaded: "Mark as Loaded",
            uploadDocsButton: "Upload Documents",
            pleaseEnterWeight: "Please enter loaded weight",
            pleaseAddDocs: "Please add documents before uploading",
            documentsUploaded: "Documents uploaded successfully",
            tripMarkedLoaded: "Trip marked as loaded",
            documentRemoved: "Document removed",
        },
        history: {
            loading: "Loading...",
            tripNotFound: "Trip not found",
            failedToLoadTrip: "Failed to load trip details",
            tripHistoryDetails: "Trip History Details",
            orderDetails: "Order Details",
            tripId: "Trip ID",
            orderId: "Order ID",
            vehicle: "Vehicle",
            weight: "Weight",
            routeTimeline: "Route & Timeline",
            assigned: "Assigned",
            started: "Started",
            completed: "Completed",
            duration: "Duration",
            pickupLocation: "Pickup Location",
            deliveryLocation: "Delivery Location",
            locationNotSpecified: "Location not specified",
            weightLoadInfo: "Weight & Load Information",
            loadedWeight: "Loaded Weight",
            deliveredWeight: "Delivered Weight",
            materialType: "Material Type",
            vehicleMake: "Vehicle Make",
            vehicleNumber: "Vehicle Number",
            paymentSummary: "Payment Summary",
            viewDetails: "View Details",
            noTripHistory: "No Trip History",
            tripHistoryEmptySubtitle: "Your completed trips will appear here.",
            yourSuccessJourney: "Your Success Journey",
            successfulDeliveries: "successful deliveries completed with excellence",
            loadingLocation: "Loading Location",
            unloadingLocation: "Unloading Location",
            notAvailable: "N/A",
            ton: "TON",
            failedToLoadTripHistory: "Failed to load trip history",
            tabLabel: "History",
        },
        language: {
            english: 'English',
            hindi: 'Hindi',
            urdu: 'Urdu',
            arabic: 'Arabic',
            chooseLanguage: 'Choose Your Language',
            selectLanguage: 'Select your preferred language to continue',
            welcome: 'Welcome',
            selectLanguageMsg: 'Please select your preferred language. You can change it later from settings.',
            continue: 'Continue',
        },
    },
    hi: {
        auth: {
            appName: "ATCE ड्राइवर",
            welcome: "स्वागत है",
            loginSubtitle: "अपनी यात्राओं और डिलीवरी को प्रबंधित करने के लिए साइन इन करें",
            emailLabel: "ईमेल पता",
            emailPlaceholder: "अपना ईमेल दर्ज करें",
            emailRequired: "ईमेल आवश्यक है",
            invalidEmail: "कृपया सही ईमेल पता दर्ज करें",
            passwordLabel: "पासवर्ड",
            passwordPlaceholder: "अपना पासवर्ड दर्ज करें",
            passwordRequired: "पासवर्ड आवश्यक है",
            passwordMin: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
            passwordMin8: "पासवर्ड कम से कम 8 अक्षरों का होना चाहिए",
            forgotPassword: "पासवर्ड भूल गए?",
            backToLogin: "लॉगिन पर वापस जाएं",
            signIn: "साइन इन करें",
            loginSuccess: "लॉगिन सफल हुआ",
            loginFailed: "लॉगिन असफल हुआ",
            enterCredentials: "कृपया ईमेल और पासवर्ड दर्ज करें",
            forgotTitle: "पासवर्ड भूल गए",
            forgotSubtitle: "अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के लिए OTP भेजेंगे",
            sendOtp: "OTP भेजें",
            otpSent: "OTP आपके ईमेल पर भेजा गया",
            otpFailed: "OTP भेजने में विफल",
            otpError: "OTP भेजा नहीं जा सका। कृपया पुनः प्रयास करें।",
            otpSendFailed: "OTP भेजने में विफल",
            otpSendError: "OTP भेजा नहीं जा सका। कृपया पुनः प्रयास करें।",
            resetTitle: "पासवर्ड रीसेट करें",
            resetSubtitle: "अपने ईमेल पर भेजा गया OTP दर्ज करें और नया पासवर्ड बनाएं",
            otpLabel: "OTP कोड",
            otpPlaceholder: "6 अंकों का OTP दर्ज करें",
            otpRequired: "OTP आवश्यक है",
            otpInvalid: "OTP 6 अंकों का होना चाहिए",
            invalidOtp: "अमान्य OTP",
            newPasswordLabel: "नया पासवर्ड",
            newPasswordPlaceholder: "नया पासवर्ड दर्ज करें",
            confirmPasswordLabel: "पासवर्ड की पुष्टि करें",
            confirmPasswordPlaceholder: "नया पासवर्ड पुनः दर्ज करें",
            confirmRequired: "कृपया पासवर्ड की पुष्टि करें",
            passwordMismatch: "पासवर्ड मेल नहीं खाते",
            resetSuccess: "पासवर्ड सफलतापूर्वक रीसेट हुआ",
            resetFailed: "पासवर्ड रीसेट नहीं हो सका। कृपया पुनः प्रयास करें।",
            didntReceive: "कोड प्राप्त नहीं हुआ?",
            resendOtp: "OTP पुनः भेजें",
            resendIn: "OTP पुनः भेजें",
            otpResent: "OTP दोबारा आपके ईमेल पर भेजा गया",
        },
        todo: {
            goodMorning: "सुप्रभात",
            goodAfternoon: "शुभ दोपहर",
            goodEvening: "शुभ संध्या",
            activeTrip: "सक्रिय यात्रा",
            totalTrips: "कुल यात्राएँ",
            viewTripDetails: "यात्रा विवरण देखें",
            noActiveTrips: "कोई सक्रिय यात्रा नहीं",
            noActiveTripsSubtitle: "आपको अभी कोई यात्रा आवंटित नहीं हुई है। रिफ्रेश करने के लिए नीचे खींचें।",
            ton: "टन",
            na: "उपलब्ध नहीं",
            tabLabel: "यात्राएँ",
            todo: "कार्य सूची",
  history: "इतिहास",
  profile: "प्रोफ़ाइल"
        },
        tripDetail: {
            title: "यात्रा विवरण",
            loading: "यात्रा विवरण लोड हो रहा है...",
            noData: "कोई यात्रा डेटा उपलब्ध नहीं",
            orderDetails: "ऑर्डर विवरण",
            tripId: "यात्रा आईडी",
            orderId: "ऑर्डर आईडी",
            vehicle: "वाहन",
            weight: "वजन",
            ton: "टन",
            activeLog: "सक्रिय लॉग",
            assigned: "आवंटित",
            started: "शुरू हुआ",
            completed: "पूर्ण हुआ",
            pickupLocation: "पिकअप स्थान",
            deliveryLocation: "डिलीवरी स्थान",
            locationNotSpecified: "स्थान निर्दिष्ट नहीं",
            noContactInfo: "कोई संपर्क जानकारी उपलब्ध नहीं",
            call: "कॉल करें",
            navigate: "नेविगेट करें",
            weightLoadInfo: "वजन और लोड जानकारी",
            deliveredWeight: "डिलीवर किया गया वजन",
            assignedWeight: "आवंटित",
            load: "लोड",
            material: "सामग्री",
            na: "उपलब्ध नहीं",
            paymentDetails: "भुगतान विवरण",
            totalAmount: "कुल राशि",
            distance: "दूरी",
            sliding: "स्लाइड हो रहा है...",
            startTrip: "यात्रा शुरू करें",
            slideStartTrip: "यात्रा शुरू करने के लिए स्लाइड करें",
            slideMarkLoaded: "लोडेड मार्क करने के लिए स्लाइड करें",
            slideMarkArrived: "पहुँच गए मार्क करने के लिए स्लाइड करें",
            slideCompleteTrip: "यात्रा पूर्ण करने के लिए स्लाइड करें",
            slideDefault: "स्लाइड",
            tripStartedSuccess: "यात्रा सफलतापूर्वक शुरू हुई!",
            invalidStatus: "वर्तमान स्थिति से यात्रा शुरू नहीं की जा सकती",
        },
        tripInProgress: {
            title: "यात्रा जारी है",
            fetchingLocation: "वर्तमान स्थान प्राप्त किया जा रहा है...",
            route: "मार्ग",
            status: "स्थिति",
            na: "उपलब्ध नहीं",
            truck: "ट्रक",
            destination: "गंतव्य",
            estimatedArrival: "अनुमानित आगमन",
            distance: "दूरी",
            deliveryLocation: "डिलीवरी स्थान",
            contactPerson: "संपर्क व्यक्ति",
            markArrived: "पहुँच गए के रूप में चिह्नित करें",
            minutesShort: "मिनट",
            hoursShort: "घंटे",
        },
        profile: {
            personalInformation: "व्यक्तिगत जानकारी",
            accountOrganization: "खाता और संगठन",
            documents: "दस्तावेज़",
            fullName: "पूरा नाम",
            email: "ईमेल",
            phoneNumber: "फ़ोन नंबर",
            userType: "उपयोगकर्ता प्रकार",
            companyName: "कंपनी का नाम",
            vehicleRegNumber: "वाहन पंजीकरण नंबर",
            signOut: "साइन आउट",
            cancel: "रद्द करें",
            logoutConfirmTitle: "साइन आउट",
            logoutConfirmMessage: "क्या आप वाकई साइन आउट करना चाहते हैं? अपनी यात्राओं तक पहुँचने के लिए आपको फिर से साइन इन करना होगा।",
            na: "उपलब्ध नहीं",
            loggedOutSuccess: "सफलतापूर्वक लॉग आउट हुआ",
            tabLabel: "प्रोफाइल",
        },
        notifications: {
            title: "सूचनाएँ",
            unread: "अपठित",
            markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
            deleteAll: "सभी हटाएँ",
            delete: "हटाएँ",
            noNotifications: "अभी तक कोई सूचना नहीं",
            loading: "लोड हो रहा है...",
        },
        markComplete: {
            header: "पूर्ण के रूप में चिह्नित करें",
            orderDetails: "ऑर्डर विवरण",
            tripId: "यात्रा आईडी",
            orderId: "ऑर्डर आईडी",
            customer: "ग्राहक",
            vehicle: "वाहन",
            weight: "वजन",
            deliveryAddress: "डिलीवरी पता",
            contact: "संपर्क",
            deliveryProgress: "डिलीवरी प्रगति",
            pickup: "पिकअप",
            loaded: "लोडेड",
            arrived: "पहुँच गए",
            complete: "पूर्ण",
            unloadedWeightLabel: "अनलोडेड वजन (टन)",
            unloadedWeightPlaceholder: "अनलोडेड वजन दर्ज करें",
            proofTitle: "डिलीवरी का प्रमाण",
            proofSubtitle: "डिलीवर किए गए पार्सल की फोटो लें",
            markButton: "पूर्ण के रूप में चिह्नित करें",
            uploadPhoto: "कृपया डिलीवरी फोटो अपलोड करें",
            enterWeight: "कृपया अनलोडेड वजन दर्ज करें",
            failed: "यात्रा पूर्ण करने में विफल",
            completed: "यात्रा सफलतापूर्वक पूर्ण हुई",
            tripCompleted: "यात्रा पूर्ण",
            deliverySuccess: "डिलीवरी सफल 🎉",
            uploaded: "फोटो सफलतापूर्वक अपलोड की गई।",
            done: "पूर्ण",
        },
        markLoad: {
            markAsLoaded: "लोडेड के रूप में चिह्नित करें",
            accessingLocation: "स्थान एक्सेस किया जा रहा है...",
            locationRequired: "स्थान आवश्यक है",
            enableLocation: "जारी रखने के लिए स्थान सेवाएँ सक्षम करें",
            retry: "पुनः प्रयास करें",
            tripLoading: "यात्रा लोड हो रही है...",
            ready: "तैयार",
            pending: "लंबित",
            allItemsLoaded: "सभी सामान सही तरीके से लोड हो गए हैं और डिलीवरी के लिए तैयार हैं",
            tripNumber: "यात्रा संख्या",
            totalWeight: "कुल वजन",
            loadedWeightLabel: "लोडेड वजन (टन)",
            loadedWeightPlaceholder: "लोडेड वजन दर्ज करें",
            uploadDocuments: "दस्तावेज़ अपलोड करें",
            uploadSubtitle: "लोडिंग प्रक्रिया के लिए फोटो लें या चुनें",
            processing: "प्रोसेस हो रहा है...",
            uploading: "अपलोड हो रहा है...",
            markTripLoaded: "लोडेड के रूप में चिह्नित करें",
            uploadDocsButton: "दस्तावेज़ अपलोड करें",
            pleaseEnterWeight: "कृपया लोडेड वजन दर्ज करें",
            pleaseAddDocs: "अपलोड करने से पहले दस्तावेज़ जोड़ें",
            documentsUploaded: "दस्तावेज़ सफलतापूर्वक अपलोड हुए",
            tripMarkedLoaded: "यात्रा लोडेड के रूप में चिह्नित हुई",
            documentRemoved: "दस्तावेज़ हटाया गया",
        },
        history: {
            loading: "लोड हो रहा है...",
            tripNotFound: "यात्रा नहीं मिली",
            failedToLoadTrip: "यात्रा विवरण लोड करने में विफल",
            tripHistoryDetails: "यात्रा इतिहास विवरण",
            orderDetails: "ऑर्डर विवरण",
            tripId: "यात्रा आईडी",
            orderId: "ऑर्डर आईडी",
            vehicle: "वाहन",
            weight: "वजन",
            routeTimeline: "मार्ग और समयरेखा",
            assigned: "आवंटित",
            started: "शुरू हुआ",
            completed: "पूर्ण हुआ",
            duration: "अवधि",
            pickupLocation: "पिकअप स्थान",
            deliveryLocation: "डिलीवरी स्थान",
            locationNotSpecified: "स्थान निर्दिष्ट नहीं",
            weightLoadInfo: "वजन और लोड जानकारी",
            loadedWeight: "लोडेड वजन",
            deliveredWeight: "डिलीवर किया गया वजन",
            materialType: "सामग्री प्रकार",
            vehicleMake: "वाहन निर्माता",
            vehicleNumber: "वाहन नंबर",
            paymentSummary: "भुगतान सारांश",
            viewDetails: "विवरण देखें",
            noTripHistory: "कोई यात्रा इतिहास नहीं",
            tripHistoryEmptySubtitle: "आपकी पूर्ण यात्राएँ यहाँ दिखाई देंगी।",
            yourSuccessJourney: "आपकी सफलता की यात्रा",
            successfulDeliveries: "सफल डिलीवरी उत्कृष्टता के साथ पूर्ण",
            loadingLocation: "लोडिंग स्थान",
            unloadingLocation: "अनलोडिंग स्थान",
            notAvailable: "उपलब्ध नहीं",
            ton: "टन",
            failedToLoadTripHistory: "यात्रा इतिहास लोड करने में विफल",
            tabLabel: "इतिहास",
        },
        language: {
            english: 'अंग्रेज़ी',
            hindi: 'हिंदी',
            urdu: 'उर्दू',
            arabic: 'अरबी',
            chooseLanguage: 'अपनी भाषा चुनें',
            selectLanguage: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें',
            welcome: 'स्वागत है',
            selectLanguageMsg: 'कृपया अपनी पसंदीदा भाषा चुनें। आप इसे बाद में सेटिंग्स से बदल सकते हैं।',
            continue: 'जारी रखें',
        },
    },

    ur: {
        auth: {
            appName: "ای ٹی سی ای ڈرائیور",
            welcome: "خوش آمدید",
            loginSubtitle: "اپنی سفروں اور ڈیلیوریز کو منظم کرنے کے لیے سائن ان کریں",
            emailLabel: "ای میل ایڈریس",
            emailPlaceholder: "اپنا ای میل درج کریں",
            emailRequired: "ای میل ضروری ہے",
            invalidEmail: "براہ کرم درست ای میل ایڈریس درج کریں",
            passwordLabel: "پاس ورڈ",
            passwordPlaceholder: "اپنا پاس ورڈ درج کریں",
            passwordRequired: "پاس ورڈ ضروری ہے",
            passwordMin: "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے",
            passwordMin8: "پاس ورڈ کم از کم 8 حروف کا ہونا چاہیے",
            forgotPassword: "پاس ورڈ بھول گئے؟",
            backToLogin: "واپس لاگ ان پر جائیں",
            signIn: "سائن ان کریں",
            loginSuccess: "لاگ ان کامیاب",
            loginFailed: "لاگ ان ناکام",
            enterCredentials: "براہ کرم ای میل اور پاس ورڈ درج کریں",
            forgotTitle: "پاس ورڈ بھول گئے",
            forgotSubtitle: "اپنا ای میل درج کریں اور ہم آپ کو پاس ورڈ ری سیٹ کرنے کے لیے OTP بھیجیں گے",
            sendOtp: "OTP بھیجیں",
            otpSent: "OTP آپ کے ای میل پر بھیج دیا گیا",
            otpFailed: "OTP بھیجنے میں ناکامی",
            otpError: "OTP نہیں بھیجا جا سکا۔ دوبارہ کوشش کریں۔",
            otpSendFailed: "OTP بھیجنے میں ناکامی",
            otpSendError: "OTP نہیں بھیجا جا سکا۔ دوبارہ کوشش کریں۔",
            resetTitle: "پاس ورڈ ری سیٹ کریں",
            resetSubtitle: "اپنے ای میل پر بھیجا گیا OTP درج کریں اور نیا پاس ورڈ بنائیں",
            otpLabel: "OTP کوڈ",
            otpPlaceholder: "6 ہندسوں کا OTP درج کریں",
            otpRequired: "OTP ضروری ہے",
            otpInvalid: "OTP 6 ہندسوں کا ہونا چاہیے",
            invalidOtp: "غلط OTP",
            newPasswordLabel: "نیا پاس ورڈ",
            newPasswordPlaceholder: "نیا پاس ورڈ درج کریں",
            confirmPasswordLabel: "پاس ورڈ کی تصدیق کریں",
            confirmPasswordPlaceholder: "نیا پاس ورڈ دوبارہ درج کریں",
            confirmRequired: "براہ کرم پاس ورڈ کی تصدیق کریں",
            passwordMismatch: "پاس ورڈ میل نہیں کھاتے",
            resetSuccess: "پاس ورڈ کامیابی سے ری سیٹ ہوا",
            resetFailed: "پاس ورڈ ری سیٹ نہیں ہو سکا۔ دوبارہ کوشش کریں۔",
            didntReceive: "کوڈ موصول نہیں ہوا؟",
            resendOtp: "OTP دوبارہ بھیجیں",
            resendIn: "OTP دوبارہ بھیجیں",
            otpResent: "OTP دوبارہ آپ کے ای میل پر بھیج دیا گیا",
        },
        todo: {
            goodMorning: "صبح بخیر",
            goodAfternoon: "دن بخیر",
            goodEvening: "شام بخیر",
            activeTrip: "فعال سفر",
            totalTrips: "کل سفر",
            viewTripDetails: "سفر کی تفصیلات دیکھیں",
            noActiveTrips: "کوئی فعال سفر نہیں",
            noActiveTripsSubtitle: "آپ کو ابھی کوئی سفر تفویض نہیں کیا گیا۔ تازہ کرنے کے لیے نیچے کھینچیں۔",
            ton: "ٹن",
            na: "دستیاب نہیں",
            tabLabel: "سفریں",
            todo: "کاموں کی فہرست",
  history: "تاریخچہ",
  profile: "پروفائل"
        },
        tripDetail: {
            title: "سفر کی تفصیلات",
            loading: "سفر کی تفصیلات لوڈ ہو رہی ہیں...",
            noData: "کوئی سفر کا ڈیٹا دستیاب نہیں",
            orderDetails: "آرڈر کی تفصیلات",
            tripId: "سفر ID",
            orderId: "آرڈر ID",
            vehicle: "گاڑی",
            weight: "وزن",
            ton: "ٹن",
            activeLog: "فعال لاگ",
            assigned: "تفویض شدہ",
            started: "شروع ہوا",
            completed: "مکمل ہوا",
            pickupLocation: "پک اپ مقام",
            deliveryLocation: "ڈیلیوری مقام",
            locationNotSpecified: "مقام مخصوص نہیں",
            noContactInfo: "کوئی رابطہ معلومات دستیاب نہیں",
            call: "کال کریں",
            navigate: "راستہ دکھائیں",
            weightLoadInfo: "وزن اور لوڈ کی معلومات",
            deliveredWeight: "ڈیلیور شدہ وزن",
            assignedWeight: "تفویض شدہ",
            load: "لوڈ",
            material: "مواد",
            na: "دستیاب نہیں",
            paymentDetails: "ادائیگی کی تفصیلات",
            totalAmount: "کل رقم",
            distance: "فاصلہ",
            sliding: "سلائیڈ ہو رہا ہے...",
            startTrip: "سفر شروع کریں",
            slideStartTrip: "سفر شروع کرنے کے لیے سلائیڈ کریں",
            slideMarkLoaded: "لوڈ شدہ نشان کرنے کے لیے سلائیڈ کریں",
            slideMarkArrived: "پہنچ گئے نشان کرنے کے لیے سلائیڈ کریں",
            slideCompleteTrip: "سفر مکمل کرنے کے لیے سلائیڈ کریں",
            slideDefault: "سلائیڈ",
            tripStartedSuccess: "سفر کامیابی سے شروع ہوا!",
            invalidStatus: "موجودہ حالت سے سفر شروع نہیں کیا جا سکتا",
        },
        tripInProgress: {
            title: "سفر جاری ہے",
            fetchingLocation: "موجودہ مقام حاصل کیا جا رہا ہے...",
            route: "راستہ",
            status: "حالت",
            na: "دستیاب نہیں",
            truck: "ٹرک",
            destination: "منزل",
            estimatedArrival: "متوقع آمد",
            distance: "فاصلہ",
            deliveryLocation: "ڈیلیوری مقام",
            contactPerson: "رابطہ شخص",
            markArrived: "پہنچ گئے کے طور پر نشان زد کریں",
            minutesShort: "منٹ",
            hoursShort: "گھنٹے",
        },
        profile: {
            personalInformation: "ذاتی معلومات",
            accountOrganization: "کھاتہ اور تنظیم",
            documents: "دستاویزات",
            fullName: "پورا نام",
            email: "ای میل",
            phoneNumber: "فون نمبر",
            userType: "صارف کی قسم",
            companyName: "کمپنی کا نام",
            vehicleRegNumber: "گاڑی کا رجسٹریشن نمبر",
            signOut: "سائن آؤٹ",
            cancel: "منسوخ کریں",
            logoutConfirmTitle: "سائن آؤٹ",
            logoutConfirmMessage: "کیا آپ واقعی سائن آؤٹ کرنا چاہتے ہیں؟ اپنی سفروں تک رسائی کے لیے دوبارہ سائن ان کرنا ہوگا۔",
            na: "دستیاب نہیں",
            loggedOutSuccess: "کامیابی سے سائن آؤٹ ہوا",
            tabLabel: "پروفائل",
        },
        notifications: {
            title: "اطلاعات",
            unread: "غیر پڑھا ہوا",
            markAllRead: "سب کو پڑھا ہوا نشان زد کریں",
            deleteAll: "سب حذف کریں",
            delete: "حذف کریں",
            noNotifications: "ابھی تک کوئی اطلاع نہیں",
            loading: "لوڈ ہو رہا ہے...",
        },
        markComplete: {
            header: "مکمل کے طور پر نشان زد کریں",
            orderDetails: "آرڈر کی تفصیلات",
            tripId: "سفر ID",
            orderId: "آرڈر ID",
            customer: "گاہک",
            vehicle: "گاڑی",
            weight: "وزن",
            deliveryAddress: "ڈیلیوری پتہ",
            contact: "رابطہ",
            deliveryProgress: "ڈیلیوری کی پیش رفت",
            pickup: "پک اپ",
            loaded: "لوڈ شدہ",
            arrived: "پہنچ گیا",
            complete: "مکمل",
            unloadedWeightLabel: "ان لوڈ شدہ وزن (ٹن)",
            unloadedWeightPlaceholder: "ان لوڈ شدہ وزن درج کریں",
            proofTitle: "ڈیلیوری کا ثبوت",
            proofSubtitle: "ڈیلیور شدہ پارسل کی تصویر لیں",
            markButton: "مکمل کے طور پر نشان زد کریں",
            uploadPhoto: "براہ کرم ڈیلیوری کی تصویر اپلوڈ کریں",
            enterWeight: "براہ کرم ان لوڈ شدہ وزن درج کریں",
            failed: "سفر مکمل کرنے میں ناکام",
            completed: "سفر کامیابی سے مکمل ہوا",
            tripCompleted: "سفر مکمل",
            deliverySuccess: "ڈیلیوری کامیاب 🎉",
            uploaded: "تصویر(یں) کامیابی سے اپلوڈ ہو گئیں۔",
            done: "مکمل",
        },
        markLoad: {
            markAsLoaded: "لوڈ شدہ کے طور پر نشان زد کریں",
            accessingLocation: "مقام حاصل کیا جا رہا ہے...",
            locationRequired: "مقام ضروری ہے",
            enableLocation: "جاری رکھنے کے لیے مقام کی خدمات فعال کریں",
            retry: "دوبارہ کوشش کریں",
            tripLoading: "سفر لوڈ ہو رہا ہے...",
            ready: "تیار",
            pending: "زیر التوا",
            allItemsLoaded: "تمام اشیاء درست طریقے سے لوڈ ہو چکی ہیں اور ڈیلیوری کے لیے تیار ہیں",
            tripNumber: "سفر نمبر",
            totalWeight: "کل وزن",
            loadedWeightLabel: "لوڈ شدہ وزن (ٹن)",
            loadedWeightPlaceholder: "لوڈ شدہ وزن درج کریں",
            uploadDocuments: "دستاویزات اپلوڈ کریں",
            uploadSubtitle: "لوڈنگ کے عمل کے لیے تصویر لیں یا منتخب کریں",
            processing: "عملدرآمد ہو رہا ہے...",
            uploading: "اپلوڈ ہو رہا ہے...",
            markTripLoaded: "لوڈ شدہ کے طور پر نشان زد کریں",
            uploadDocsButton: "دستاویزات اپلوڈ کریں",
            pleaseEnterWeight: "براہ کرم لوڈ شدہ وزن درج کریں",
            pleaseAddDocs: "اپلوڈ کرنے سے پہلے دستاویزات شامل کریں",
            documentsUploaded: "دستاویزات کامیابی سے اپلوڈ ہو گئیں",
            tripMarkedLoaded: "سفر لوڈ شدہ کے طور پر نشان زد ہوا",
            documentRemoved: "دستاویز ہٹا دی گئی",
        },
        history: {
            loading: "لوڈ ہو رہا ہے...",
            tripNotFound: "سفر نہیں ملا",
            failedToLoadTrip: "سفر کی تفصیلات لوڈ کرنے میں ناکام",
            tripHistoryDetails: "سفر کی تاریخ کی تفصیلات",
            orderDetails: "آرڈر کی تفصیلات",
            tripId: "سفر ID",
            orderId: "آرڈر ID",
            vehicle: "گاڑی",
            weight: "وزن",
            routeTimeline: "راستہ اور ٹائم لائن",
            assigned: "تفویض شدہ",
            started: "شروع ہوا",
            completed: "مکمل ہوا",
            duration: "مدت",
            pickupLocation: "پک اپ مقام",
            deliveryLocation: "ڈیلیوری مقام",
            locationNotSpecified: "مقام مخصوص نہیں",
            weightLoadInfo: "وزن اور لوڈ کی معلومات",
            loadedWeight: "لوڈ شدہ وزن",
            deliveredWeight: "ڈیلیور شدہ وزن",
            materialType: "مواد کی قسم",
            vehicleMake: "گاڑی کا برانڈ",
            vehicleNumber: "گاڑی نمبر",
            paymentSummary: "ادائیگی کا خلاصہ",
            viewDetails: "تفصیلات دیکھیں",
            noTripHistory: "کوئی سفر کی تاریخ نہیں",
            tripHistoryEmptySubtitle: "آپ کی مکمل شدہ سفریں یہاں ظاہر ہوں گی۔",
            yourSuccessJourney: "آپ کا کامیابی کا سفر",
            successfulDeliveries: "کامیاب ڈیلیوریز عمدگی کے ساتھ مکمل",
            loadingLocation: "لوڈنگ مقام",
            unloadingLocation: "ان لوڈنگ مقام",
            notAvailable: "دستیاب نہیں",
            ton: "ٹن",
            failedToLoadTripHistory: "سفر کی تاریخ لوڈ کرنے میں ناکام",
            tabLabel: "ہسٹری",
        },
        language: {
            english: 'انگریزی',
            hindi: 'ہندی',
            urdu: 'اردو',
            arabic: 'عربی',
            chooseLanguage: 'اپنی زبان منتخب کریں',
            selectLanguage: 'جاری رکھنے کے لیے اپنی پسندیدہ زبان منتخب کریں',
            welcome: 'خوش آمدید',
            selectLanguageMsg: 'براہ کرم اپنی پسندیدہ زبان منتخب کریں۔ آپ بعد میں اسے سیٹنگز سے تبدیل کر سکتے ہیں۔',
            continue: 'جاری رکھیں',
        },
    },

    ar: {
        auth: {
            appName: "سائق ATCE",
            welcome: "مرحبًا",
            loginSubtitle: "قم بتسجيل الدخول لإدارة رحلاتك وتسليماتك",
            emailLabel: "البريد الإلكتروني",
            emailPlaceholder: "أدخل بريدك الإلكتروني",
            emailRequired: "البريد الإلكتروني مطلوب",
            invalidEmail: "يرجى إدخال بريد إلكتروني صالح",
            passwordLabel: "كلمة المرور",
            passwordPlaceholder: "أدخل كلمة المرور",
            passwordRequired: "كلمة المرور مطلوبة",
            passwordMin: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
            passwordMin8: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
            forgotPassword: "هل نسيت كلمة المرور؟",
            backToLogin: "العودة لتسجيل الدخول",
            signIn: "تسجيل الدخول",
            loginSuccess: "تم تسجيل الدخول بنجاح",
            loginFailed: "فشل تسجيل الدخول",
            enterCredentials: "يرجى إدخال البريد الإلكتروني وكلمة المرور",
            forgotTitle: "نسيت كلمة المرور",
            forgotSubtitle: "أدخل بريدك الإلكتروني وسنرسل لك OTP لإعادة تعيين كلمة المرور",
            sendOtp: "إرسال OTP",
            otpSent: "تم إرسال OTP إلى بريدك الإلكتروني",
            otpFailed: "فشل إرسال OTP",
            otpError: "تعذر إرسال OTP. يرجى المحاولة مرة أخرى.",
            otpSendFailed: "فشل إرسال OTP",
            otpSendError: "تعذر إرسال OTP. يرجى المحاولة مرة أخرى.",
            resetTitle: "إعادة تعيين كلمة المرور",
            resetSubtitle: "أدخل OTP المرسل إلى بريدك الإلكتروني وأنشئ كلمة مرور جديدة",
            otpLabel: "رمز OTP",
            otpPlaceholder: "أدخل OTP المكون من 6 أرقام",
            otpRequired: "رمز OTP مطلوب",
            otpInvalid: "يجب أن يكون OTP مكونًا من 6 أرقام",
            invalidOtp: "رمز OTP غير صالح",
            newPasswordLabel: "كلمة المرور الجديدة",
            newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
            confirmPasswordLabel: "تأكيد كلمة المرور",
            confirmPasswordPlaceholder: "أدخل كلمة المرور الجديدة مرة أخرى",
            confirmRequired: "يرجى تأكيد كلمة المرور",
            passwordMismatch: "كلمتا المرور غير متطابقتين",
            resetSuccess: "تم إعادة تعيين كلمة المرور بنجاح",
            resetFailed: "تعذر إعادة تعيين كلمة المرور. يرجى المحاولة مرة أخرى.",
            didntReceive: "لم يصلك الرمز؟",
            resendOtp: "إعادة إرسال OTP",
            resendIn: "إعادة إرسال OTP في",
            otpResent: "تم إعادة إرسال OTP إلى بريدك الإلكتروني",
        },
        todo: {
            goodMorning: "صباح الخير",
            goodAfternoon: "مساء الخير",
            goodEvening: "مساء الخير",
            activeTrip: "رحلة نشطة",
            totalTrips: "إجمالي الرحلات",
            viewTripDetails: "عرض تفاصيل الرحلة",
            noActiveTrips: "لا توجد رحلات نشطة",
            noActiveTripsSubtitle: "لم يتم تعيين أي رحلات لك بعد. اسحب لتحديث.",
            ton: "طن",
            na: "غير متاح",
            tabLabel: "الرحلات",
            todo: "قائمة المهام",
  history: "السجل",
  profile: "الملف الشخصي"
        },
        tripDetail: {
            title: "تفاصيل الرحلة",
            loading: "جاري تحميل تفاصيل الرحلة...",
            noData: "لا توجد بيانات للرحلة",
            orderDetails: "تفاصيل الطلب",
            tripId: "معرّف الرحلة",
            orderId: "معرّف الطلب",
            vehicle: "المركبة",
            weight: "الوزن",
            ton: "طن",
            activeLog: "السجل النشط",
            assigned: "مُعيّن",
            started: "بدأت",
            completed: "مكتمل",
            pickupLocation: "موقع الالتقاط",
            deliveryLocation: "موقع التسليم",
            locationNotSpecified: "الموقع غير محدد",
            noContactInfo: "لا توجد معلومات اتصال",
            call: "اتصل",
            navigate: "التوجيه",
            weightLoadInfo: "معلومات الوزن والحمل",
            deliveredWeight: "الوزن المسلّم",
            assignedWeight: "المعيّن",
            load: "الحمل",
            material: "المادة",
            na: "غير متاح",
            paymentDetails: "تفاصيل الدفع",
            totalAmount: "المبلغ الإجمالي",
            distance: "المسافة",
            sliding: "جارٍ السحب...",
            startTrip: "ابدأ الرحلة",
            slideStartTrip: "اسحب لبدء الرحلة",
            slideMarkLoaded: "اسحب لتعليم التحميل",
            slideMarkArrived: "اسحب لتعليم الوصول",
            slideCompleteTrip: "اسحب لإكمال الرحلة",
            slideDefault: "اسحب",
            tripStartedSuccess: "تم بدء الرحلة بنجاح!",
            invalidStatus: "لا يمكن بدء الرحلة من الحالة الحالية",
        },
        tripInProgress: {
            title: "الرحلة جارية",
            fetchingLocation: "جاري الحصول على الموقع الحالي...",
            route: "المسار",
            status: "الحالة",
            na: "غير متاح",
            truck: "الشاحنة",
            destination: "الوجهة",
            estimatedArrival: "الوصول المقدر",
            distance: "المسافة",
            deliveryLocation: "موقع التسليم",
            contactPerson: "الشخص المسؤول",
            markArrived: "علم بوصوله",
            minutesShort: "دقيقة",
            hoursShort: "ساعة",
        },
        profile: {
            personalInformation: "المعلومات الشخصية",
            accountOrganization: "الحساب والمنظمة",
            documents: "المستندات",
            fullName: "الاسم الكامل",
            email: "البريد الإلكتروني",
            phoneNumber: "رقم الهاتف",
            userType: "نوع المستخدم",
            companyName: "اسم الشركة",
            vehicleRegNumber: "رقم تسجيل المركبة",
            signOut: "تسجيل الخروج",
            cancel: "إلغاء",
            logoutConfirmTitle: "تسجيل الخروج",
            logoutConfirmMessage: "هل أنت متأكد أنك تريد تسجيل الخروج؟ ستحتاج لتسجيل الدخول مرة أخرى للوصول إلى رحلاتك.",
            na: "غير متاح",
            loggedOutSuccess: "تم تسجيل الخروج بنجاح",
            tabLabel: "الملف الشخصي",
        },
        notifications: {
            title: "الإشعارات",
            unread: "غير مقروء",
            markAllRead: "وضع علامة مقروء على الكل",
            deleteAll: "حذف الكل",
            delete: "حذف",
            noNotifications: "لا توجد إشعارات بعد",
            loading: "جاري التحميل...",
        },
        markComplete: {
            header: "علم كمكتمل",
            orderDetails: "تفاصيل الطلب",
            tripId: "معرّف الرحلة",
            orderId: "معرّف الطلب",
            customer: "العميل",
            vehicle: "المركبة",
            weight: "الوزن",
            deliveryAddress: "عنوان التسليم",
            contact: "الاتصال",
            deliveryProgress: "تقدم التسليم",
            pickup: "الاستلام",
            loaded: "تم التحميل",
            arrived: "وصل",
            complete: "مكتمل",
            unloadedWeightLabel: "الوزن غير المحمّل (طن)",
            unloadedWeightPlaceholder: "أدخل الوزن غير المحمّل",
            proofTitle: "إثبات التسليم",
            proofSubtitle: "التقط صورة للطرود المسلّمة",
            markButton: "علم كمكتمل",
            uploadPhoto: "يرجى تحميل صورة التسليم",
            enterWeight: "يرجى إدخال الوزن غير المحمّل",
            failed: "فشل في إكمال الرحلة",
            completed: "تم إكمال الرحلة بنجاح",
            tripCompleted: "تمت الرحلة",
            deliverySuccess: "تم التسليم بنجاح 🎉",
            uploaded: "تم تحميل صورة/صور بنجاح.",
            done: "مكتمل",
        },
        markLoad: {
            markAsLoaded: "علم كمحمّل",
            accessingLocation: "جاري الوصول إلى الموقع...",
            locationRequired: "الموقع مطلوب",
            enableLocation: "قم بتمكين خدمات الموقع للمتابعة",
            retry: "أعد المحاولة",
            tripLoading: "جاري تحميل الرحلة...",
            ready: "جاهز",
            pending: "قيد الانتظار",
            allItemsLoaded: "تم تحميل جميع العناصر بشكل صحيح وجاهزة للتسليم",
            tripNumber: "رقم الرحلة",
            totalWeight: "الوزن الكلي",
            loadedWeightLabel: "الوزن المحمّل (طن)",
            loadedWeightPlaceholder: "أدخل الوزن المحمّل",
            uploadDocuments: "تحميل المستندات",
            uploadSubtitle: "التقط صوراً أو اخترها لعملية التحميل",
            processing: "جاري المعالجة...",
            uploading: "جاري التحميل...",
            markTripLoaded: "علم كمحمّل",
            uploadDocsButton: "تحميل المستندات",
            pleaseEnterWeight: "يرجى إدخال الوزن المحمّل",
            pleaseAddDocs: "يرجى إضافة مستندات قبل التحميل",
            documentsUploaded: "تم تحميل المستندات بنجاح",
            tripMarkedLoaded: "تم تعليم الرحلة كمحمّلة",
            documentRemoved: "تمت إزالة المستند",
        },
        history: {
            loading: "جاري التحميل...",
            tripNotFound: "لم يتم العثور على الرحلة",
            failedToLoadTrip: "فشل تحميل تفاصيل الرحلة",
            tripHistoryDetails: "تفاصيل تاريخ الرحلة",
            orderDetails: "تفاصيل الطلب",
            tripId: "معرّف الرحلة",
            orderId: "معرّف الطلب",
            vehicle: "المركبة",
            weight: "الوزن",
            routeTimeline: "المسار والجدول الزمني",
            assigned: "مُعيّن",
            started: "بدأت",
            completed: "مكتمل",
            duration: "المدة",
            pickupLocation: "موقع الالتقاط",
            deliveryLocation: "موقع التسليم",
            locationNotSpecified: "الموقع غير محدد",
            weightLoadInfo: "معلومات الوزن والحمل",
            loadedWeight: "الوزن المحمّل",
            deliveredWeight: "الوزن المسلّم",
            materialType: "نوع المادة",
            vehicleMake: "صنع المركبة",
            vehicleNumber: "رقم المركبة",
            paymentSummary: "ملخص الدفع",
            viewDetails: "عرض التفاصيل",
            noTripHistory: "لا يوجد سجل رحلة",
            tripHistoryEmptySubtitle: "ستظهر رحلاتك المكتملة هنا.",
            yourSuccessJourney: "رحلتك الناجحة",
            successfulDeliveries: "تم إكمال التسليمات بنجاح وبتميز",
            loadingLocation: "جاري تحميل الموقع",
            unloadingLocation: "موقع التفريغ",
            notAvailable: "غير متاح",
            ton: "طن",
            failedToLoadTripHistory: "فشل تحميل سجل الرحلة",
        },
        language: {
            english: 'الإنجليزية',
            hindi: 'الهندية',
            urdu: 'الأردية',
            arabic: 'العربية',
            chooseLanguage: 'اختر لغتك',
            selectLanguage: 'اختر لغتك المفضلة للمتابعة',
            welcome: 'مرحبًا',
            selectLanguageMsg: 'يرجى اختيار لغتك المفضلة. يمكنك تغييرها لاحقًا من الإعدادات.',
            continue: 'استمر',
        },
    },
});

export default strings;



